version: '3.9'

services:
  #new service (java_app)
  molinic_backend:
    container_name: molinic_backend
    image: hector451/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://database_molinic:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - database_molinic

  #old service (postgres)
  database_molinic:
    container_name: database_molinic
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  molinic_frontend:
    container_name: molinic_frontend
    build:
      context: /home/hectorla/Escritorio/MolinicFrontEnd/Front  # Ruta al directorio del frontend
    ports:
      - 5173:5173  # Puerto del frontend
    depends_on:
      - molinic_backend  # Asegura que el backend esté en ejecución antes del frontend

volumes:
  pgdata: {}

